### PR TITLE
Have WebView load once per fragment lifecycle, instead of repeatedly.

### PR DESCRIPTION
**Pull request by arislomovic**

### CODE REVIEW

**Comment by arislomovic** [comment]
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/801

**Comment by payamazadi** [comment]
👍

**Comment by lnfnunes** [comment]
👍

**Comment by janrk-ciandt** [comment]
@rpdome Could you please take a look at this PR? This is an important issue that needs to be addressed.

**Comment by rpdome** [comment]
@arislomovic Thanks for catching the bug. Would you mind signing the CLA in the other PR?

**Comment by arislomovic** [comment]
@rpdome I actually did, but for some reason the thread in the last PR doesn't reflect that. Not sure how to fix that

**Pull request closed without merging**
