### PR TITLE
[Major | API Breaking] SSOStateSerializer Moving Out of Internal Package

### PR DESCRIPTION
**Pull request by iambmelt**
Impetus:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1333714?src=WorkItemMention&src-action=artifact_link

Summary:
- OneAuth is depending on this `internal` class to enable use of TSL/AccountDiscovery
- OneAuth ideally shouldn't have to 'drill into' this otherwise default visibility class, so moving out of `internal`
- This is API breaking for Android-Common, since OneAuth is known to have a dependency on this class
- This change _could_ be additive if we elected to duplicate the class and `@deprecate` the old one; I elected to move it and change the vis instead

### CODE REVIEW

**Comment by AdamBJohnsonx** [comment]
Should we add an entry somewhere to a document describing what changes consumers will need to make?

**Comment by iambmelt** [comment]
> Should we add an entry somewhere to a document describing what changes consumers will need to make?

@AdamBJohnsonx For this particular change, I have a PBI tracking here - I can update it with the new pkg name OneAuth will need to use to consume this class:
https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1333714

**Comment by AdamBJohnsonx** [comment]
I was 

> > Should we add an entry somewhere to a document describing what changes consumers will need to make?
> 
> @AdamBJohnsonx For this particular change, I have a PBI tracking here - I can update it with the new pkg name OneAuth will need to use to consume this class:
> https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1333714

I was hoping for a consolidated list somewhere. ;-)

**Comment by AdamBJohnsonx** [comment]
> I was
> 
> > > Should we add an entry somewhere to a document describing what changes consumers will need to make?
> > 
> > 
> > @AdamBJohnsonx For this particular change, I have a PBI tracking here - I can update it with the new pkg name OneAuth will need to use to consume this class:
> > https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1333714
> 
> I was hoping for a consolidated list somewhere. ;-)

In the absence of that, can we short-url-link it in the changelog?

**Comment by iambmelt** [comment]
> > I was
> > > > Should we add an entry somewhere to a document describing what changes consumers will need to make?
> > > 
> > > 
> > > @AdamBJohnsonx For this particular change, I have a PBI tracking here - I can update it with the new pkg name OneAuth will need to use to consume this class:
> > > https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1333714
> > 
> > 
> > I was hoping for a consolidated list somewhere. ;-)
> 
> In the absence of that, can we short-url-link it in the changelog?

ACK - we should plan to make this doc... for the time I'll make a shortlink in the changelog to this PBI

**Review by AdamBJohnsonx — APPROVED** [review]

**Review by rpdome — APPROVED** [review]

**Pull request merged**
