### PR TITLE
Add js injection for test cases

### PR DESCRIPTION
**Pull request by rpdome**
MSAL CPP Team would like to inject JS as part of their test suites.
(I intentionally don't expose this in createStartIntent())

### CODE REVIEW

**Comment by iambmelt** [comment]
This looks like something we need to think about / threat model before merging since this looks like something a bad actor could conceivably leverage to display phishing content, screen scrape or otherwise. 

I'm also a little apprehensive about the variable/field naming, as this looks to me generally a way to override the navigation URL rather than an [explicit API for injecting javascript into WebView](https://github.com/iambmelt/WebViewInjector) (shameless plug, sorry 😅)

**Comment by iambmelt** [comment]
> This looks like something we need to think about / threat model before merging since this looks like something a bad actor could conceivably leverage to display phishing content, screen scrape or otherwise.
> 
> I'm also a little apprehensive about the variable/field naming, as this looks to me generally a way to override the navigation URL rather than an explicit API for injecting javascript into a WebView

@rpdome Can you support this _only_ if this is a `DEBUG` build?

**Comment by rpdome** [comment]
> > This looks like something we need to think about / threat model before merging since this looks like something a bad actor could conceivably leverage to display phishing content, screen scrape or otherwise.
> > I'm also a little apprehensive about the variable/field naming, as this looks to me generally a way to override the navigation URL rather than an explicit API for injecting javascript into a WebView
> 
> @rpdome Can you support this _only_ if this is a `DEBUG` build?

I think that should be fine.

**Comment by iambmelt** [comment]
> > > This looks like something we need to think about / threat model before merging since this looks like something a bad actor could conceivably leverage to display phishing content, screen scrape or otherwise.
> > > I'm also a little apprehensive about the variable/field naming, as this looks to me generally a way to override the navigation URL rather than an explicit API for injecting javascript into a WebView
> > 
> > 
> > @rpdome Can you support this _only_ if this is a `DEBUG` build?
> 
> EDIT: Just realized that this might not work for them as they'll be consuming the release build of common.

Synced offline. Since this uses the same mechanism as our standing `loadUrl` function (which has already been sec reviewed / modeled) these changes are likely OK. Will still review in standup

**Pull request merged**
