### PR TITLE
Disregard pageload errors for non-primary-frame

### PR DESCRIPTION
**Pull request by iambmelt**
Impetus
- https://portal.microsofticm.com/imp/v3/incidents/details/239658713/home

Summary:
Suppose an ADFS sign-in page is customized to include an iframe of custom content; page load errors inside of that frame should not prevent a user from being able to sign-in. [This change drops events from the "non-primary frame".](https://stackoverflow.com/questions/44068123/how-to-detect-errors-only-from-the-main-page-in-new-onreceivederror-from-webview)

This change needed only on the API 23 overload, as the default behavior prior to this override was to drop these events.

Testing:
Manual testing against a real-life ADFS instance with this problem. See above linked IcM.

### CODE REVIEW

**Comment by iambmelt** [comment]
Update changelog

**Comment by iambmelt** [comment]
Assuming this PR is approved, ADAL needs a similar change here:
https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/BasicWebViewClient.java#L167-L173

**Comment by iambmelt** [comment]
> Update changelog

284cecf6bccee01be01f2fb11c2c0c9c82e46387

**Comment by iambmelt** [comment]
CI failing with errors not related to my changes

**Comment by iambmelt** [comment]
@p3dr0rv ^^

**Comment by iamgusain** [comment]
Added some comments in the ADAL PR, 
otherwise LGTM

**Review by iamgusain — APPROVED** [review]
:shipit:

**Comment by p3dr0rv** [comment]
> @p3dr0rv ^^

https://identitydivision.visualstudio.com/Engineering/_build/results?buildId=772142&view=results

**Review by rpdome — APPROVED** [review]

**Pull request merged**
