### PR TITLE
Fix the onCancel when back button got clicked

### PR DESCRIPTION
**Pull request by heidijinxujia**

### CODE REVIEW

**Comment by alfetch** [comment]
HI @heidijinxujia .. Now i can see you have fixed this, but how do i get the code.. I can see it's not released for gradle ?

**Comment by heidijinxujia** [comment]
Hi @alfetch Thank you for following up here. This fix is currently under code review and will be published in our next regular MSAL release. Are you trying to test it or you are waiting for a release for your app?

**Comment by alfetch** [comment]
@heidijinxujia If i should test it from dev, then i have to fork the project from dev or how? Right now i'm only referring to the release 0.2.1 from gradle. When will a new regular release happend?

**Comment by alfetch** [comment]
@heidijinxujia I just got the new 0.2.2 from gradle maven.. I can't see there is a fix for this ?

**Comment by iambmelt** [comment]
Hi @alfetch - The `changelog` and [Releases ](https://github.com/AzureAD/microsoft-authentication-library-for-android/releases/tag/v0.2.2)page contain up-to-date information on the contents on these releases. This fix was not prioritized for our last release.

**Comment by heidijinxujia** [comment]
Thank you for the review! Comment addressed. @iambmelt

**Pull request merged**
