### PR TITLE
Added fields to PublicApiId.java

### PR DESCRIPTION
**Pull request by fadidurah**
Small PR to add needed fields in PublicApiId.java to support new methods for api change PR: https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1595

### CODE REVIEW

**Review by tanmaymanolkar1 — COMMENTED** [review]
Why not assign values to these added APIs?

**Comment by fadidurah** [comment]
> Why not assign values to these added APIs?

I was wondering what the best values to assign would be, here.

**Comment by fadidurah** [comment]
I went ahead and added some ids, i'm not sure if they are overlapping with any existing ids

**Review by shoatman — APPROVED** [review]
lgtm

**Review by tanmaymanolkar1 — APPROVED** [review]

**Review by gitaumoses4 — APPROVED** [review]

**Pull request merged**
