### PR TITLE
Melissaahn/remove new config changes

### PR DESCRIPTION
**Pull request by melissaahn**
Creating this for the new release branch.

### CODE REVIEW

**Comment by gitaumoses4** [comment]
@shahzaibj seems here we'll be removing all of the Yubikit changes.

**Comment by shahzaibj** [comment]
@melissaahn I thought we didn't need to remove all the changes?

**Comment by melissaahn** [comment]
I had to remove all changes that included or used the YubiKit Sdk. There are some remaining changes from my PR that just shifted around some sections (the ClientCertAuthChallengeHandler class, for example), but those don't depend on YubiKit.

**Comment by melissaahn** [comment]
If the question is about bumping to 5.0.0.... since Yubikit is not included, and Java version 8 is not included. nor needed to be included in the host app anymore, I'm thinking that the version number does not need to be moved to 5 anymore. I forgot to remove my changelog line, so I'll do that right now.

**Comment by shahzaibj** [comment]
> I had to remove all changes that included or used the YubiKit Sdk. There are some remaining changes from my PR that just shifted around some sections (the ClientCertAuthChallengeHandler class, for example), but those don't depend on YubiKit.

Why was this needed?

**Comment by melissaahn** [comment]
> > I had to remove all changes that included or used the YubiKit Sdk. There are some remaining changes from my PR that just shifted around some sections (the ClientCertAuthChallengeHandler class, for example), but those don't depend on YubiKit.
> 
> Why was this needed?

When the Authenticator team attempted to add a work account in their testing, they got a NoClassDefFoundError in regard to the YubiKitManager class. I'm not sure why this is happening, as they shouldn't need to include any of the YubiKit dependencies (should be taken care of by common). It seems that I need to do more testing before including these dependencies, so I was thinking that the quickest fix to unblock the release is to take out all the YubiKit code.

**Comment by shahzaibj** [comment]
> > > I had to remove all changes that included or used the YubiKit Sdk. There are some remaining changes from my PR that just shifted around some sections (the ClientCertAuthChallengeHandler class, for example), but those don't depend on YubiKit.
> > 
> > 
> > Why was this needed?
> 
> When the Authenticator team attempted to add a work account in their testing, they got a NoClassDefFoundError in regard to the YubiKitManager class. I'm not sure why this is happening, as they shouldn't need to include any of the YubiKit dependencies (should be taken care of by common). It seems that I need to do more testing before including these dependencies, so I was thinking that the quickest fix to unblock the release is to take out all the YubiKit code.

Okay, sounds good.

I think the version number for our release will still remain at `5.0.0` because I see there is another MAJOR change in the changelog.

**Review by shahzaibj — APPROVED** [review]

**Pull request merged**
