### PR TITLE
Fix issue where default scopes are not set

### PR DESCRIPTION
**Pull request by kreedula**
- Adding default scopes to `Operation parameters` o initialization
issue : https://github.com/AzureAD/ad-accounts-for-android/issues/827

### CODE REVIEW

**Comment by iambmelt** [comment]
Should we consider using a Set to hold the scopes? How do we ensure that scopes don't get added multiple times?

**Comment by kreedula** [comment]
Set would have been nicer, but needs some API changes w.r.t Msal and also probably public facing API. For now I have added logic in the set method here to avoid duplication here : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/383/files#diff-37c9340cd26ba11cb1d207ed29a72f9bR67

**Comment by iambmelt** [comment]
Yuck - we should make a backlog item for that. As for that check, you'll want to trim() and do the check as case insensitive -- the case for a Set (with a proper Comparator) getting stronger already 😅

**Comment by iambmelt** [comment]
I can make it in the morning, currently on a mobile

**Comment by kreedula** [comment]
Thanks @iambmelt , I will add a backlog item, scopes are case sensitive per rfc [here ](https://tools.ietf.org/html/rfc6749#section-3.3). Trimming is good idea.

**Comment by shoatman** [comment]
I added a comment to your other PR on this topic.  FYI - In AAD scopes are not case sensitive.  One of the reasons that we moved validation of requests to the strategy associated with the issuer.  Some IDPs will follow the spec and others will not.

**Comment by kreedula** [comment]
Closing this , opened a new one here : https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/386

**Pull request closed without merging**
