### PR TITLE
Fixing the Authenticator RedirectURI in broker

### PR DESCRIPTION
**Pull request by tanmaymanolkar1**
Address the issue :
Broker redirect uri is invalid. Expected: urn:ietf:wg:oauth:2.0:oob Actual: msauth://.......

### CODE REVIEW

**Review by AdamBJohnsonx — APPROVED** [review]
Only question would be if the test coverage we have adequately covers this case.

**Comment by tanmaymanolkar1** [comment]
> Only question would be if the test coverage we have adequately covers this case.


I am passing this RC1 to authenticator team to test this one out

**Comment by AdamBJohnsonx** [comment]
Disabling branch protection to get around spurious test failure.

**Comment by tanmaymanolkar1** [comment]
ran ./gradlew clean common:assemble locally whcih works, hence merging this

**Pull request merged**
