### PR TITLE
Merge release/v3.1.1 to master

### PR DESCRIPTION
**Pull request by gitaumoses4**

### CODE REVIEW

**Comment by shahzaibj** [comment]
Have we already done the testing?

**Comment by shahzaibj** [comment]
Unless the testing and verification is done, this can't be called 3.1.1

it needs to be an RC version such as 3.1.1-RC1

**Comment by gitaumoses4** [comment]
Hi Shahzaib. From the release docs by @rpdome , it says I should cut both branches. 3.1.1 and 3.1.1-RC1

**Comment by shahzaibj** [comment]
> Hi Shahzaib. From the release docs by @rpdome , it says I should cut both branches. 3.1.1 and 3.1.1-RC1

I'm not worried about branches....I'm worried about what we've put here in version.properties file..I see it says 3.1.1...but we can't go there until we've verified the RCs

**Comment by gitaumoses4** [comment]
> > Hi Shahzaib. From the release docs by @rpdome , it says I should cut both branches. 3.1.1 and 3.1.1-RC1
> 
> I'm not worried about branches....I'm worried about what we've put here in version.properties file..I see it says 3.1.1...but we can't go there until we've verified the RCs

Oh, I see. I've created the RC1 PR.

**Pull request closed without merging**
