### PR TITLE
Added child parameters to CommandParameters for OneAuth to set them

### PR DESCRIPTION
**Pull request by somalaya**
In nested app authentication flow, broker needs to query ESTS with nested app's clientid and redirectUri. To allow OneAuth to set this, we have added child parameters to command parameters.

### CODE REVIEW

**Review by rpdome — APPROVED** [review]
please add comment/javadoc describing what they're for.

**Review by mohitc1 — APPROVED** [review]
:shipit:

**Comment by shahzaibj** [comment]
Where would these be read in our code?

I have not made any changes to read these in our code. Nick just needs to use this PR to integrate on OneAuth side while I make changes parallely in broker read them

**Comment by iamgusain** [comment]
Can you add little bit more in the PR description for future context.
Why we need this change.

**Comment by somalaya** [comment]
> Where would these be read in our code?



> Can you add little bit more in the PR description for future context. Why we need this change.

done

**Pull request merged**
