### PR TITLE
merge master to release/4.0.0

### PR DESCRIPTION
**Pull request by iamgusain**
### What is in the change
Merging changes from master branch to release/4.0.0
- This merge brings changes in releases 3.6.4 and 3.6.5 to release/4.0.0

### CODE REVIEW

**Comment by AdamBJohnsonx** [comment]
Conmon4j failing

**Comment by AdamBJohnsonx** [comment]
> Conmon4j failing

It’s release… nvm

**Review by AdamBJohnsonx — APPROVED** [review]

**Comment by p3dr0rv** [comment]
@iamgusain I see some errors in the instrumented test pipeline https://identitydivision.visualstudio.com/fac9d424-53d2-45c0-91b5-ef6ba7a6bf26/_apis/build/builds/847605/logs/12
are we going to handle these errors in the release branch later?

**Comment by iamgusain** [comment]
> @iamgusain I see some errors in the instrumented test pipeline https://identitydivision.visualstudio.com/fac9d424-53d2-45c0-91b5-ef6ba7a6bf26/_apis/build/builds/847605/logs/12 are we going to handle these errors in the release branch later?

cherry picked the fix from dev branch

**Pull request merged**
