### PR TITLE
Fix the discrepancy on "mIdentityProvider" caused in adal v1.15.1

### LINKED ISSUE #343: [Regression] discrepancy on "mIdentityProvider" of Account object between v1.14.1 and v1.15.1
There is a discrepancy on "mIdentityProvider" of Account object between v1.14.1 and v1.15.1

1. The identity provider is returned by V1. So `mIdentityProvider` should be a property of `AzureActiveDirectoryAccount` object instead of `MicrosoftAccount`.
2.  The identity provider should be valued with `idp` idtoken claim instead of `iss` claim.

### PR DESCRIPTION
**Pull request by heidijinxujia**
There is a discrepancy on "mIdentityProvider" of Account object between v1.14.1 and v1.15.1

1. The identity provider is returned by V1. So `mIdentityProvider` should be a property of `AzureActiveDirectoryAccount` object instead of `MicrosoftAccount`.
2.  The identity provider should be valued with `idp` idtoken claim instead of `iss` claim.

Close #343

### CODE REVIEW

**Comment by iambmelt** [comment]
@heidijinxujia Please don't merge this until I get a chance to review, thanks

**Comment by iambmelt** [comment]
@heidijinxujia Can you link to the PR where this changed? There is likely a justification; I want to make sure we're not breaking MSAL to fix ADAL

**Comment by iambmelt** [comment]
At a glance, these changes make sense: the naming is clearer for sure.

**Comment by heidijinxujia** [comment]
It's been one week. I am going to merge this PR.

**Comment by iambmelt** [comment]
@heidijinxujia why was this merged? We have to merge the hotfix from master to dev containing this fix anyway

Did teams sign off on the fix?

**Comment by heidijinxujia** [comment]
Teams said they were not going to verify this fix.

**Pull request merged**
