### PR TITLE
Fix ServiceSpecificException on Android9.

### PR DESCRIPTION
**Pull request by masahiro-ikemoto**
Fix ServiceSpecificException on Android9.
See: https://stackoverflow.com/questions/52024752/android-9-keystore-exception-android-os-servicespecificexception

### CODE REVIEW

**Comment by iambmelt** [comment]
Related https://github.com/AzureAD/microsoft-authentication-library-common-for-android/issues/317

**Comment by masahiro-ikemoto** [comment]
What's happened on [checking Build](https://travis-ci.org/AzureAD/microsoft-authentication-library-common-for-android/builds/548765137)?
I can build the branch successfully.

**Comment by iambmelt** [comment]
@masahiro-ikemoto Is this change to _suppress_ the logged exception or were you experiencing a crash as a result of this?

**Comment by masahiro-ikemoto** [comment]
In the current implementation, have no problem prior to Android9, but app crashes on Android9 (at least in Google Pixel3 XL).

Yes, the method is not marked as deprecated, but exception is [reported](https://www.google.com/search?q=android+keystore+getentry+ServiceSpecificException) from multiple peoples.

I don't know why the exception occurs. It may be related [Restrictions non sdk interfaces](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces).

**Comment by iambmelt** [comment]
Related: [Adal/#1439](https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/1439) has instances of this logged exception in its trace.

**Comment by iambmelt** [comment]
Thanks for this info @masahiro-ikemoto -- I'll be pulling down these changes to review today

**Comment by iambmelt** [comment]
Changes tested and working on Huawei Nexus 6P.

OS ver: 8.1.0
Security patch: Dec 5, 18

**Comment by iambmelt** [comment]
Thank you for your contribution @masahiro-ikemoto 

I have merged your change to dev, it will be tracked for a future release.

**Pull request merged**
