### PR TITLE
Allow WebView Zoom Toggle #908

### PR DESCRIPTION
**Pull request by arislomovic**

### CODE REVIEW

**Comment by payamazadi** [comment]
👍

**Comment by wmiranda** [comment]
@rpdome could you please review it? tks in adv

**Comment by rpdome** [comment]
@arislomovic May I ask what are the scenarios you're trying to achieve with this PR? (or what are the issues you were running into with the current code).

**Comment by arislomovic** [comment]
Right now the webview has certain settings hard coded in this library. This code allow the users to toggle any of those settings to their liking. In our case it'd mean turning off the zoom.

**Pull request closed without merging**
