### PR TITLE
Add homeAccountId to BaseException

### PR DESCRIPTION
**Pull request by iamgusain**
### What
Adding homeAccountId field in BaseException class to pass the homeAccountId information to errorHandler

### Why
The interactive requests do not have the homeAccountId field populated to begin with. But this field is required to be returned back to application when we return IntuneAppProtecttionPolicyRequiredException. Otherwise applicaiton failed to do MAM registration.

### How
Adding homeAccountId field in BaseException, and exposing a method to set it.

### Testing
This change is part of fixing the bug https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1998929/
Verified the scenario where Teams app could not sign in if user (with MAM and MFA policies) sign out once or if user tries to sign in after device registration
The changes to setHomeAccountId fields are in this Broker PR https://github.com/AzureAD/ad-accounts-for-android/pull/1975

### CODE REVIEW

**Review by shahzaibj — CHANGES_REQUESTED** [review]
We are returning `IntuneAppProtectionPolicyRequiredException` as opposed to `BaseException` right? So why do we need user id here on BaseException? I mean we are already exposing user id on `IntuneAppProtectionPolicyRequiredException` so apps should be using that.

**Comment by iamgusain** [comment]
> We are returning `IntuneAppProtectionPolicyRequiredException` as opposed to `BaseException` right? So why do we need user id here on BaseException? I mean we are already exposing user id on `IntuneAppProtectionPolicyRequiredException` so apps should be using that.

We don't have the homeAccountId populated when we are creating IntuneAppProtectionPolicyRequiredException. This change is to enable passing homeAccountId so that we can return the IntuneAppProtectionPolicyRequiredException with it.
Corresponding Broker PR https://github.com/AzureAD/ad-accounts-for-android/pull/1975

**Comment by shahzaibj** [comment]
> > We are returning `IntuneAppProtectionPolicyRequiredException` as opposed to `BaseException` right? So why do we need user id here on BaseException? I mean we are already exposing user id on `IntuneAppProtectionPolicyRequiredException` so apps should be using that.
> 
> We don't have the homeAccountId populated when we are creating IntuneAppProtectionPolicyRequiredException. This change is to enable passing homeAccountId so that we can return the IntuneAppProtectionPolicyRequiredException with it. Corresponding Broker PR [AzureAD/ad-accounts-for-android#1975](https://github.com/AzureAD/ad-accounts-for-android/pull/1975)

I think populating it totally makes sense. My question was more about why we are populating it on BaseException as opposed to IntuneAppProtectionPolicyRequiredException?

**Comment by iamgusain** [comment]
Closing this PR. As we no longer need this change. See updated PR in broker https://github.com/AzureAD/ad-accounts-for-android/pull/1975

**Pull request closed without merging**
