### PR TITLE
Fix for ISSUE-915 (https://github.com/AzureAD/microsoft-authenticatio…

### PR DESCRIPTION
**Pull request by xyzwilliamxyz**
…n-library-for-android/issues/915)

Hi, this is a fix for the issue that is commented on this issue

### CODE REVIEW

**Comment by iambmelt** [comment]
Thanks for your submission @xyzwilliamxyz -- @shoatman brought me up to speed on the issue you're facing in B2C.

I am going to fork off your changes and make some additional tweaks to account for scenarios that exist exterior to B2C; I am also going to prepare these changes for another branch that we can use to expedite the rollout process for these fixes.

I'm going to leave your PR open until I have opened by addendum PR and will link these two work items together

**Comment by xyzwilliamxyz** [comment]
@iambmelt Understood. Thank you.

**Comment by iambmelt** [comment]
Superseded by:
https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/811

@xyzwilliamxyz Please take a look at the above PR which expands upon your proposed changes and provide any feedback. Thanks.

**Comment by xyzwilliamxyz** [comment]
Looks good to me!

**Pull request closed without merging**
